### PR TITLE
Automated the process using an API 

### PR DESCRIPTION
**Pull request by ReversableCode**

### CODE REVIEW

**Comment by ReversableCode** [comment]
The death and recovery counter isn't automated yet. I am still working on it since the api that I use doesn't provide them.

**Comment by mehdibo** [comment]
Do we have the right to use this API?

**Comment by mehdibo** [comment]
> The death and recovery counter isn't automated yet, I am still working on it since the api that I use doesn't provide them.

I can see in the API that there is this count, what's the problem with it?

**Comment by ReversableCode** [comment]
that counter is missing two deaths thats why.

**Comment by ReversableCode** [comment]
to avoid problems, I was thinking of making a wrapper api.

**Comment by mehdibo** [comment]
Also the idea of depending on an unofficial API bothers me, we depend on this provider to give the correct and most up to date data, where we could just scrap [this official one](http://covidmaroc.ma/).

I was fiddling with OCR for the image yesterday and it was working well, maybe a combination of OCR and parsing the HTML to extract data is a better approach (the image is updated more frequently)

[The OCR library](https://github.com/tesseract-ocr/tessdoc)

**Comment by mehdibo** [comment]
Also check the examples here:
https://github.com/naptha/tesseract.js#tesseractjs

**Comment by ReversableCode** [comment]
ok sounds good and interesting to me

**Comment by mehdibo** [comment]
Check again the website, it is no longer an image so we no longer need OCR you can just scrape the HTML

**Comment by ReversableCode** [comment]
@mehdibo I was working on OCR before they changed it, but unfortunately I am facing problems with CORS when I try to scrap the HTML now.

**Comment by mehdibo** [comment]
You shouldn't have CORS problems because the code is not going to be executed in a browser, I will configure a Github Action to run your code (node your_code.js)

**Comment by ReversableCode** [comment]
Ok

**Pull request closed without merging**
