### PR TITLE
 Minor changes for better user experience

### PR DESCRIPTION
**Pull request by EniddeallA**
- Disabled scrolling through the page
- Minor CSS changes
- Minor changes in react elements structure

### CODE REVIEW

**Comment by mehdibo** [comment]
Is it possible to make it responsive?

**Comment by EniddeallA** [comment]
working on it

**Comment by EniddeallA** [comment]
As of @ReversableCode already done a great job on styling the page I only left the 'unscrollable' change and fixed merge conflicts.

**Comment by mehdibo** [comment]
I will close this as it was already fixed #17.
If I merge this some changes will be undone.

Thank you so much!

**Pull request closed without merging**
