### PR TITLE
Updated the map

### PR DESCRIPTION
**Pull request by ReversableCode**
changed the map to another open sourced map.

### CODE REVIEW

**Comment by mehdibo** [comment]
This also has a splitted map

**Comment by ReversableCode** [comment]
at lease it doesn't say western sahara. The problem is that openstreetmap is the only one that provides open sourced maps and the others are plan based.

**Comment by ReversableCode** [comment]
this map that I suggested is also openstreetmap's map but in another flavor.

**Comment by mehdibo** [comment]
I don't know... for me the one you submitted splits it in half, I think it's even worse than the first one. We should look for something, someone told me about maps with the [d3js library](https://d3js.org/), if you have time you can look it up.

**Comment by ReversableCode** [comment]
Ok I'll look it up.

**Pull request closed without merging**
